server:
  port: 0

spring:
  application:
    name: todo-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_NAME}
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/${KEYCLOAK_REALM_NAME}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/${KEYCLOAK_REALM_NAME}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka-server

  instance:
    instance-id: ${spring.application.name}:${random.uuid}

kafka:
  topic-name: ${KAFKA_TOPIC_NAME}
  group-id: ${KAFKA_GROUP_ID}

elastic:
  host: ${ELASTIC_HOST}
  port: ${ELASTIC_PORT}